### ISSUE TITLE
Cuda Udacity course link problem

### ISSUE THREAD

**Issue by mhepeyiler** [MattPD/cpplinks#13]
Hi Matt, thanks for the sharing this repo. But I would like to point that Cuda course on Udacity that named is Intro to Parallel Programming CS344 does not accessible anymore.  Could you fix it if it is possible? I searched the course on google but I could not find it.

**Comment by MattPD** [comment]
Done in https://github.com/MattPD/cpplinks/commit/64504860b3a436a9179248bb17ae63cc7709ebac -- thanks!
