### ISSUE TITLE
Sorry for contacting you in that way

### ISSUE THREAD

**Issue by mzer0-yu** [MattPD/cpplinks#2]
Hello Matt. I am happy having a same interest with you in C/C++! Thought how many people loving C/C++, using it in projects, talking about its things, mastering it, but sometimes I feel lonely with it. Many programming languages have its own community, like python, JS, golang, perl, rubby...People like using "modern" languages to build their own projects and that is increasing and more and more popular. I can't find a good community to discuss C/C++ things. Although we have boost and cpp standard communities, but they are more about technology. In fact, we can do almost everything in C/C++, as easy as those "modern" languages. For those reasons, I want to set up a micro-community for C/C++ engineers talking about anything, sharing own projects written in C/C++, and it is non-native English speaker friendly. I use [an IRC channel on slack](https://xonce.slack.com/messages/engineers/) now(it is not an AD), hope you will like it.

**Comment by mzer0-yu** [comment]
@MattPD Oops...Slack doesn't allow to join a team in that way. Anyway if you have interest I can send you an invitation email...

**Comment by MattPD** [comment]
@mzer0-yu It's OK -- this gives support for an idea to add a list of on-line communities, so I'm keeping this as an issue to address :-)

**Comment by ChopsII** [comment]
a couple of links...

reddit.com/r/cpp
reddit.com/r/cppquestions

cpplang.slack.com (get an invite from https://cpplang.now.sh/ )

**Comment by MattPD** [comment]
Thank you, @ChopsII! :-)

Added two new collections (in b9b688557d75e0ef293f2ce6afcfd81ed18a636e):

- [Communities](https://github.com/MattPD/cpplinks/blob/master/communities.md)
- [Learning and Teaching](https://github.com/MattPD/cpplinks/blob/master/learning_teaching.md)

Hopefully this will be of help to the folks learning (and teaching) C++ -- aren't we all, after all :-)
