### ISSUE TITLE
add new courses

### ISSUE THREAD

**Issue by hardboydu** [MattPD/cpplinks#26]
Added courses [stanford cs149] and [CMU 15-418] to the [atomics, lock free, memory model] chapter

**Comment by MattPD** [comment]
Hi! Is this possibly missing a pull request?
I've noticed that CS149 only has three introductory lectures on this topic (and a lot of pretty good parallel computing lectures); so this area may be already well covered.
As far as I can tell there are no resources (e.g., lecture videos) for https://www.cs.cmu.edu/~418/schedule.html
