### ISSUE TITLE
FFI: improvement

### ISSUE THREAD

**Issue by kassane** [MattPD/cpplinks#30]
## Suggestion

* Nim to C and C++ interop

Compiler backend: https://nim-lang.org/docs/backends.html#interfacing-nim-code-calling-the-backend

FFI: https://nimbus.guide/auditors-book/02.5_foreign_lang_to_from_interop.html

https://github.com/nim-lang/csources_v1
https://github.com/nim-lang/c2nim
https://github.com/nimterop/nimterop

* Zig to C interop

Working with C: https://ziglearn.org/chapter-4/
Goodbye C++ impl:
https://ziglang.org/news/goodbye-cpp/

Learn FFI:
https://ziglang.org/learn/overview/#integration-with-c-libraries-without-ffibindings

Zig extend C/C++:
https://zig.news/kristoff/extend-a-c-c-project-with-zig-55di

Swift => C => Zig: https://zig.news/kristoff/sharing-types-between-zig-and-swift-part-1-22cm

**Comment by MattPD** [comment]
Thanks. Added Nim resources in [411ea5d](https://github.com/MattPD/cpplinks/commit/411ea5dcfa3bae4cdc2544aeb49eee5e91c32f9d) (some were no longer active or up-to-date: skipped). Will take a look at the Zig resources, hopefully later this month (if not, feel free to ping me in February).

**Comment by kassane** [comment]
> Thanks. Added Nim resources in [411ea5d](https://github.com/MattPD/cpplinks/commit/411ea5dcfa3bae4cdc2544aeb49eee5e91c32f9d) (some were no longer active or up-to-date: skipped).

Recent article:
https://scripter.co/binding-nim-to-c-plus-plus-std-list/

>Will take a look at the Zig resources, hopefully later this month (if not, feel free to ping me in February).

Ok!

**Comment by MattPD** [comment]
Done in [0f1f7ba](https://github.com/MattPD/cpplinks/commit/0f1f7ba1bae0b5b07467dfc5019ed017d99e0714); thanks!

**Comment by kassane** [comment]
@MattPD ,

https://github.com/lassade/c2z (transpiling C++ to Zig w/clang ast)
