### ISSUE TITLE
Caching: more sw

### ISSUE THREAD

**Issue by mbitsnbites** [MattPD/cpplinks#9]
You may want to add the following cache tools:

* [BuildCache](https://github.com/mbitsnbites/buildcache)
* [clcache](https://github.com/frerich/clcache)

**Comment by MattPD** [comment]
Thanks!

clcache.py is under https://github.com/MattPD/cpplinks/blob/master/building.md#visual-studio; noticed that BuildCache is in the early development stage for now (focusing on production ready caching software at the moment), but will keep an eye on it!
